version: '3'
services:
  postgresql:
    image: "postgres:latest"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=marten
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: 12345
